# Generated by Django 3.2.5 on 2021-09-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_yorummodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IletisimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('isim_soyisim', models.CharField(max_length=150)),
                ('mesaj', models.TextField()),
                ('olusturmaTarihi', models.DateTimeField(auto_now_add=True)),
                ('resim', models.ImageField(upload_to='yazi_resimleri')),
            ],
            options={
                'verbose_name': 'İletisim',
                'verbose_name_plural': 'İletişimler',
                'db_table': 'iletisim',
            },
        ),
    ]
