# Generated by Django 3.2.5 on 2021-09-16 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_iletisimmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iletisimmodel',
            name='resim',
        ),
    ]
