# Generated by Django 3.2.5 on 2021-09-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_iletisimmodel_resim'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IletisimModel',
            new_name='IletiModel',
        ),
        migrations.AlterModelOptions(
            name='iletimodel',
            options={'verbose_name': 'İleti', 'verbose_name_plural': 'İletiler'},
        ),
        migrations.AlterModelTable(
            name='iletimodel',
            table='ileti',
        ),
    ]
