# Generated by Django 3.2.5 on 2021-09-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210916_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='IletisimiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('isim_soyisim', models.CharField(max_length=150)),
                ('mesaj', models.TextField()),
                ('olusturmaTarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'İletisimi',
                'verbose_name_plural': 'İletisimiler',
                'db_table': 'iletisimi',
            },
        ),
        migrations.DeleteModel(
            name='IletiModel',
        ),
    ]
