# Generated by Django 3.2.5 on 2021-09-16 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210916_1734'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IletisimiModel',
            new_name='IletisimModel',
        ),
        migrations.AlterModelOptions(
            name='iletisimmodel',
            options={'verbose_name': 'İletisim', 'verbose_name_plural': 'İletisimler'},
        ),
        migrations.AlterModelTable(
            name='iletisimmodel',
            table='iletisim',
        ),
    ]
