# Generated by Django 3.2.5 on 2021-09-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210916_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yazilarmodel',
            options={'verbose_name': 'Yazı', 'verbose_name_plural': 'Yazılar'},
        ),
    ]
